--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0

-- Started on 2024-12-16 22:28:27

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_namespace WHERE nspname = 'public') THEN
        CREATE SCHEMA public;
    END IF;
END
$$;

ALTER SCHEMA public OWNER TO pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

SET default_tablespace = '';
SET default_table_access_method = heap;

--
-- TOC entry 238 (class 1259 OID 17013)
-- Name: application_history; Type: TABLE; Schema: public; Owner: pim_admin
--

CREATE TABLE public.application_history (
    id integer NOT NULL,
    student_id character varying(255) NOT NULL,
    application_type character varying(255) NOT NULL,
    status character varying(255) DEFAULT 'pending'::character varying,
    submission_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    processed_date timestamp without time zone,
    processed_by character varying(255),
    remarks character varying(255),
    appointment_date character varying(255),
    end_month character varying(255),
    start_month character varying(255),
    register_id bigint,
    special_request character varying(255),
    request_id integer
);


ALTER TABLE public.application_history OWNER TO pim_admin;

--
-- TOC entry 237 (class 1259 OID 17012)
-- Name: application_history_id_seq; Type: SEQUENCE; Schema: public; Owner: pim_admin
--

CREATE SEQUENCE public.application_history_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.application_history_id_seq OWNER TO pim_admin;

--
-- TOC entry 3490 (class 0 OID 0)
-- Dependencies: 237
-- Name: application_history_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: pim_admin
--

ALTER SEQUENCE public.application_history_id_seq OWNED BY public.application_history.id;


--
-- TOC entry 234 (class 1259 OID 16841)
-- Name: post_news; Type: TABLE; Schema: public; Owner: pim_admin
--

CREATE TABLE public.post_news (
    id bigint NOT NULL,
    content character varying(255) NOT NULL,
    create_date timestamp(6) without time zone,
    image_data character varying(255),
    image_name character varying(255),
    image_type character varying(255),
    image_names character varying(255)
);


ALTER TABLE public.post_news OWNER TO pim_admin;

--
-- TOC entry 233 (class 1259 OID 16840)
-- Name: post_news_id_seq; Type: SEQUENCE; Schema: public; Owner: pim_admin
--

ALTER TABLE public.post_news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16513)
-- Name: rankin_activityk_entities; Type: TABLE; Schema: public; Owner: pim_admin
--

CREATE TABLE public.rankin_activityk_entities (
    id bigint NOT NULL,
    activity_name character varying(255),
    hours double precision,
    student_id character varying(255)
);


ALTER TABLE public.rankin_activityk_entities OWNER TO pim_admin;

--
-- TOC entry 231 (class 1259 OID 16512)
-- Name: rankin_activityk_entities_id_seq; Type: SEQUENCE; Schema: public; Owner: pim_admin
--

ALTER TABLE public.rankin_activityk_entities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rankin_activityk_entities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16473)
-- Name: request; Type: TABLE; Schema: public; Owner: pim_admin
--

CREATE TABLE public.request (
    id integer NOT NULL,
    student_id character varying(255),
    first_name character varying(255),
    special_request character varying(255),
    create_date timestamp without time zone
);


ALTER TABLE public.request OWNER TO pim_admin;

--
-- TOC entry 223 (class 1259 OID 16472)
-- Name: request_id_seq; Type: SEQUENCE; Schema: public; Owner: pim_admin
--

CREATE SEQUENCE public.request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.request_id_seq OWNER TO pim_admin;

--
-- TOC entry 3491 (class 0 OID 0)
-- Dependencies: 223
-- Name: request_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: pim_admin
--

ALTER SEQUENCE public.request_id_seq OWNED BY public.request.id;


--
-- TOC entry 242 (class 1259 OID 17192)
-- Name: scholarship; Type: TABLE; Schema: public; Owner: pim_admin
--

CREATE TABLE public.scholarship (
    id integer NOT NULL,
    academic_year character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.scholarship OWNER TO pim_admin;

--
-- TOC entry 241 (class 1259 OID 17191)
-- Name: scholarship_id_seq; Type: SEQUENCE; Schema: public; Owner: pim_admin
--

CREATE SEQUENCE public.scholarship_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.scholarship_id_seq OWNER TO pim_admin;

--
-- TOC entry 3492 (class 0 OID 0)
-- Dependencies: 241
-- Name: scholarship_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: pim_admin
--

ALTER SEQUENCE public.scholarship_id_seq OWNED BY public.scholarship.id;


--
-- TOC entry 240 (class 1259 OID 17183)
-- Name: scholarship_img; Type: TABLE; Schema: public; Owner: pim_admin
--

CREATE TABLE public.scholarship_img (
    id integer NOT NULL,
    student_id character varying(255),
    first_name character varying(255),
    image_name character varying(255),
    image_data character varying(255),
    create_date timestamp without time zone,
    image_type character varying(255)
);


ALTER TABLE public.scholarship_img OWNER TO pim_admin;

--
-- TOC entry 239 (class 1259 OID 17182)
-- Name: scholarship_img_id_seq; Type: SEQUENCE; Schema: public; Owner: pim_admin
--

CREATE SEQUENCE public.scholarship_img_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.scholarship_img_id_seq OWNER TO pim_admin;

--
-- TOC entry 3493 (class 0 OID 0)
-- Dependencies: 239
-- Name: scholarship_img_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: pim_admin
--

ALTER SEQUENCE public.scholarship_img_id_seq OWNED BY public.scholarship_img.id;


--
-- TOC entry 230 (class 1259 OID 16503)
-- Name: specialwork; Type: TABLE; Schema: public; Owner: pim_admin
--

CREATE TABLE public.specialwork (
    id bigint NOT NULL,
    student_id character varying(255),
    first_name character varying(255),
    work_name character varying(255),
    organization_name character varying(255),
    work_type character varying(255),
    work_description character varying(255),
    compensation character varying(255),
    work_dates character varying(255),
    work_time character varying(255),
    create_date timestamp without time zone,
    hour integer,
    prefix character varying(255),
    nickname character varying(255),
    graduate character varying(255),
    branch character varying(255),
    activity_date character varying(255),
    organization_phone character varying(255)
);


ALTER TABLE public.specialwork OWNER TO pim_admin;

--
-- TOC entry 229 (class 1259 OID 16502)
-- Name: specialwork_id_seq; Type: SEQUENCE; Schema: public; Owner: pim_admin
--

CREATE SEQUENCE public.specialwork_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.specialwork_id_seq OWNER TO pim_admin;

--
-- TOC entry 3494 (class 0 OID 0)
-- Dependencies: 229
-- Name: specialwork_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: pim_admin
--

ALTER SEQUENCE public.specialwork_id_seq OWNED BY public.specialwork.id;


--
-- TOC entry 218 (class 1259 OID 16437)
-- Name: specialwork_img; Type: TABLE; Schema: public; Owner: pim_admin
--

CREATE TABLE public.specialwork_img (
    id integer NOT NULL,
    student_id character varying(255),
    first_name character varying(255),
    image_name character varying(255),
    image_data character varying(255),
    create_date timestamp without time zone,
    image_type character varying(255),
    specialwork_id character varying(255)
);


ALTER TABLE public.specialwork_img OWNER TO pim_admin;

--
-- TOC entry 217 (class 1259 OID 16436)
-- Name: specialwork_img_id_seq; Type: SEQUENCE; Schema: public; Owner: pim_admin
--

CREATE SEQUENCE public.specialwork_img_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.specialwork_img_id_seq OWNER TO pim_admin;

--
-- TOC entry 3495 (class 0 OID 0)
-- Dependencies: 217
-- Name: specialwork_img_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: pim_admin
--

ALTER SEQUENCE public.specialwork_img_id_seq OWNED BY public.specialwork_img.id;


--
-- TOC entry 236 (class 1259 OID 17003)
-- Name: student; Type: TABLE; Schema: public; Owner: pim_admin
--

CREATE TABLE public.student (
    id integer NOT NULL,
    student_id character varying(255),
    prefix character varying(255),
    first_name character varying(255),
    thai_name character varying(255),
    last_name character varying(255),
    nickname character varying(255),
    date_of_birth character varying(255),
    gender character varying(255),
    national_id character varying(255),
    email character varying(255),
    phone_number character varying(255),
    faculty character varying(255),
    field_of_study character varying(255),
    currently_studying_year character varying(255),
    student_type character varying(255),
    block character varying(255),
    current_gpa numeric(38,2),
    create_date timestamp without time zone,
    place_of_study character varying(255),
    other_place character varying(255),
    current_address character varying(255),
    student_resident character varying(255),
    number_of_residents integer,
    current_province character varying(255),
    current_district character varying(255),
    current_subdistrict character varying(255),
    current_postal_code character varying(255),
    address_according_to_house_registration character varying(255),
    province character varying(255),
    district character varying(255),
    subdistrict character varying(255),
    postal_code character varying(255),
    advisor_name_surname character varying(255),
    advisor_phone_number character varying(255),
    know_the_pim_smart_fund_from character varying(255),
    additional_details character varying(255),
    scholarship_received character varying(255),
    other_scholarships character varying(255),
    education_loan character varying(255),
    graduated_from_school character varying(255),
    province_school character varying(255),
    line_id character varying(255),
    facebook character varying(255),
    father_name_surname character varying(255),
    mother_name_surname character varying(255),
    occupation_father character varying(255),
    occupation_mother character varying(255),
    estimate_father_monthly_income character varying(255),
    mother_approximate_monthly_income character varying(255),
    father_address character varying(255),
    father_address_details character varying(255),
    mother_address character varying(255),
    mother_address_details character varying(255),
    congenital_disease character varying(255),
    paternal_memory_disorder character varying(255),
    maternal_memory_disorder character varying(255),
    father_status character varying(255),
    father_status_details character varying(255),
    maternal_status character varying(255),
    maternal_status_details character varying(255),
    have_siblings character varying(255),
    woman character varying(255),
    address_value character varying(255),
    round_trip_travel character varying(255),
    household_expenses character varying(255),
    family_debt character varying(255),
    contact_information character varying(255),
    emergency_contact character varying(255),
    relationship character varying(255),
    emergency_contact_phone_number character varying(255),
    beauty_enhancement character varying(255),
    beauty_enhancement_details character varying(255),
    man character varying(255),
    person_who character varying(255),
    parent_information character varying(255),
    talent character varying(255),
    primary_education character varying(255),
    middle_school character varying(255),
    high_school character varying(255),
    current character varying(255),
    special_work character varying(255),
    hope character varying(255),
    committee character varying(255),
    family_history character varying(255),
    special_request character varying(255),
    update_date timestamp(6) without time zone
);


ALTER TABLE public.student OWNER TO pim_admin;

--
-- TOC entry 235 (class 1259 OID 17002)
-- Name: student_id_seq; Type: SEQUENCE; Schema: public; Owner: pim_admin
--

CREATE SEQUENCE public.student_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.student_id_seq OWNER TO pim_admin;

--
-- TOC entry 3496 (class 0 OID 0)
-- Dependencies: 235
-- Name: student_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: pim_admin
--

ALTER SEQUENCE public.student_id_seq OWNED BY public.student.id;


--
-- TOC entry 222 (class 1259 OID 16455)
-- Name: students_img; Type: TABLE; Schema: public; Owner: pim_admin
--

CREATE TABLE public.students_img (
    id integer NOT NULL,
    student_id character varying(255),
    first_name character varying(255),
    image_name character varying(255),
    image_data character varying(255),
    create_date timestamp without time zone,
    image_type character varying(255),
    register_id bigint
);


ALTER TABLE public.students_img OWNER TO pim_admin;

--
-- TOC entry 221 (class 1259 OID 16454)
-- Name: students_img_id_seq; Type: SEQUENCE; Schema: public; Owner: pim_admin
--

CREATE SEQUENCE public.students_img_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.students_img_id_seq OWNER TO pim_admin;

--
-- TOC entry 3497 (class 0 OID 0)
-- Dependencies: 221
-- Name: students_img_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: pim_admin
--

ALTER SEQUENCE public.students_img_id_seq OWNED BY public.students_img.id;


--
-- TOC entry 226 (class 1259 OID 16480)
-- Name: users; Type: TABLE; Schema: public; Owner: pim_admin
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    token character varying(255),
    create_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    update_date timestamp(6) without time zone
);


ALTER TABLE public.users OWNER TO pim_admin;

--
-- TOC entry 225 (class 1259 OID 16479)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: pim_admin
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO pim_admin;

--
-- TOC entry 3498 (class 0 OID 0)
-- Dependencies: 225
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: pim_admin
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- TOC entry 228 (class 1259 OID 16494)
-- Name: volunteeractivity; Type: TABLE; Schema: public; Owner: pim_admin
--

CREATE TABLE public.volunteeractivity (
    id bigint NOT NULL,
    student_id character varying(255),
    first_name character varying(255),
    activity_name character varying(255),
    organization_name character varying(255),
    organization_phone character varying(255),
    activity_description text,
    activity_date character varying(255),
    hours integer,
    create_date timestamp without time zone,
    prefix character varying(255),
    nickname character varying(255),
    graduate character varying(255),
    branch character varying(255)
);


ALTER TABLE public.volunteeractivity OWNER TO pim_admin;

--
-- TOC entry 227 (class 1259 OID 16493)
-- Name: volunteeractivity_id_seq; Type: SEQUENCE; Schema: public; Owner: pim_admin
--

CREATE SEQUENCE public.volunteeractivity_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.volunteeractivity_id_seq OWNER TO pim_admin;

--
-- TOC entry 3499 (class 0 OID 0)
-- Dependencies: 227
-- Name: volunteeractivity_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: pim_admin
--

ALTER SEQUENCE public.volunteeractivity_id_seq OWNED BY public.volunteeractivity.id;


--
-- TOC entry 220 (class 1259 OID 16446)
-- Name: volunteeractivity_img; Type: TABLE; Schema: public; Owner: pim_admin
--

CREATE TABLE public.volunteeractivity_img (
    id integer NOT NULL,
    student_id character varying(255),
    first_name character varying(255),
    image_name character varying(255),
    image_data character varying(255),
    create_date timestamp without time zone,
    image_type character varying(255),
    volunteerid character varying(255),
    volunteer_id character varying(255)
);


ALTER TABLE public.volunteeractivity_img OWNER TO pim_admin;

--
-- TOC entry 219 (class 1259 OID 16445)
-- Name: volunteeractivity_img_id_seq; Type: SEQUENCE; Schema: public; Owner: pim_admin
--

CREATE SEQUENCE public.volunteeractivity_img_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.volunteeractivity_img_id_seq OWNER TO pim_admin;

--
-- TOC entry 3500 (class 0 OID 0)
-- Dependencies: 219
-- Name: volunteeractivity_img_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: pim_admin
--

ALTER SEQUENCE public.volunteeractivity_img_id_seq OWNED BY public.volunteeractivity_img.id;


--
-- TOC entry 3280 (class 2604 OID 17016)
-- Name: application_history id; Type: DEFAULT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.application_history ALTER COLUMN id SET DEFAULT nextval('public.application_history_id_seq'::regclass);


--
-- TOC entry 3273 (class 2604 OID 16520)
-- Name: request id; Type: DEFAULT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.request ALTER COLUMN id SET DEFAULT nextval('public.request_id_seq'::regclass);


--
-- TOC entry 3284 (class 2604 OID 17195)
-- Name: scholarship id; Type: DEFAULT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.scholarship ALTER COLUMN id SET DEFAULT nextval('public.scholarship_id_seq'::regclass);


--
-- TOC entry 3283 (class 2604 OID 17186)
-- Name: scholarship_img id; Type: DEFAULT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.scholarship_img ALTER COLUMN id SET DEFAULT nextval('public.scholarship_img_id_seq'::regclass);


--
-- TOC entry 3278 (class 2604 OID 16526)
-- Name: specialwork id; Type: DEFAULT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.specialwork ALTER COLUMN id SET DEFAULT nextval('public.specialwork_id_seq'::regclass);


--
-- TOC entry 3270 (class 2604 OID 16440)
-- Name: specialwork_img id; Type: DEFAULT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.specialwork_img ALTER COLUMN id SET DEFAULT nextval('public.specialwork_img_id_seq'::regclass);


--
-- TOC entry 3279 (class 2604 OID 17006)
-- Name: student id; Type: DEFAULT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.student ALTER COLUMN id SET DEFAULT nextval('public.student_id_seq'::regclass);


--
-- TOC entry 3272 (class 2604 OID 16458)
-- Name: students_img id; Type: DEFAULT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.students_img ALTER COLUMN id SET DEFAULT nextval('public.students_img_id_seq'::regclass);


--
-- TOC entry 3274 (class 2604 OID 16483)
-- Name: users id; Type: DEFAULT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- TOC entry 3277 (class 2604 OID 16757)
-- Name: volunteeractivity id; Type: DEFAULT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.volunteeractivity ALTER COLUMN id SET DEFAULT nextval('public.volunteeractivity_id_seq'::regclass);


--
-- TOC entry 3271 (class 2604 OID 16449)
-- Name: volunteeractivity_img id; Type: DEFAULT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.volunteeractivity_img ALTER COLUMN id SET DEFAULT nextval('public.volunteeractivity_img_id_seq'::regclass);


--
-- TOC entry 3479 (class 0 OID 17013)
-- Dependencies: 238
-- Data for Name: application_history; Type: TABLE DATA; Schema: public; Owner: pim_admin
--

COPY public.application_history (id, student_id, application_type, status, submission_date, processed_date, processed_by, remarks, appointment_date, end_month, start_month, register_id, special_request, request_id) FROM stdin;
62	6452100602	admin_registration	complete	2024-11-21 21:14:17.536873	2024-11-23 21:52:04.024499	admin	\N	20/11/24 04:00	23/12/25	23/12/24	22	Admin registered new student	\N
71	1234567890558	initial_application	pending	2024-11-24 21:40:20.575133	\N	\N	\N	\N	\N	\N	29	\N	\N
74	S010	initial_application	rejected	2024-12-04 22:57:58.422699	2024-12-08 21:49:03.263074	admin	\N	\N	\N	\N	30	\N	\N
\.


--
-- TOC entry 3475 (class 0 OID 16841)
-- Dependencies: 234
-- Data for Name: post_news; Type: TABLE DATA; Schema: public; Owner: pim_admin
--

COPY public.post_news (id, content, create_date, image_data, image_name, image_type, image_names) FROM stdin;
1	aaaaaaaaaaaaaaaaaa	2024-11-24 20:20:19.911921	1vcfY3a5--LRh_2mpVWGsuzFVXuI00acn	\N	ImageNews	beautiful-young-woma.jpg
4	fdfdfdf	2024-12-01 18:53:40.286583	15owpJoRmsUwM6esv2JUzSyJP0BDBoS_K,1aMg2_-ENKY83P5vM3yems_wMIJ3DBve4	\N	ImageNews	beautiful-young-woma.jpg
5	gfgf	2024-12-15 00:07:36.781734	1nH0QtMhVgbJEHj_8pk7zyXAvDB3CEmO2	\N	ImageNewsPost	screencapture-pimsmart-onrender-Scholarship-2024-12-12-22_34_07.png
6	ffff	2024-12-15 00:08:06.870132	19Tub0CjLsNANCxXfNk-Bl3SNYjYvdFtM	\N	ImageNewsPost	pdf-file.png
\.


--
-- TOC entry 3473 (class 0 OID 16513)
-- Dependencies: 232
-- Data for Name: rankin_activityk_entities; Type: TABLE DATA; Schema: public; Owner: pim_admin
--

COPY public.rankin_activityk_entities (id, activity_name, hours, student_id) FROM stdin;
\.


--
-- TOC entry 3465 (class 0 OID 16473)
-- Dependencies: 224
-- Data for Name: request; Type: TABLE DATA; Schema: public; Owner: pim_admin
--

COPY public.request (id, student_id, first_name, special_request, create_date) FROM stdin;
2	S010	Sophia	\N	2024-11-05 22:38:47.594411
3	6452100602	Suhaimee	Helloword	2024-11-05 22:46:15.967549
4	6452100602	Suhaimee	wwwwwwwwwwww	2024-11-06 21:05:05.979166
5	S010	Sophia	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa	2024-11-10 21:57:35.871802
6	S010	Sophia	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa	2024-11-10 21:57:41.819461
7	S010	Sophia	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa	2024-11-10 22:04:53.692865
8	S010	Sophia	aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa	2024-11-10 22:07:34.303703
9	S010	Sophia	xxxxxxxxxxxxxxxxxxxxxx	2024-11-10 22:08:01.602036
10	S010	Sophia	หกกกกกกก	2024-11-10 22:17:55.685033
11	S010	Sophia	sdddds	2024-11-10 22:18:15.339586
12	S010	Sophia	aaaaaaaaaaaaaaaaaaaa	2024-11-10 22:20:41.631997
13	S010	Sophia	dddddddddd	2024-11-10 22:21:45.064958
1	6452100602	Suhaimee	ปปปปปปปปปปปปปปปปปปปปปปปปปปปปปปปปปปปปปปปปป	2024-11-05 20:38:43.95791
14	S010	Sophia	xxxxxxxxxxxxxxx	2024-11-12 22:08:20.32283
15	S010	Sophia	xxxxxxxxxxxxxxx	2024-11-12 22:08:24.998274
16	S88990	Carlos	หกหหหหหหหหหหหหหหหหหหหห	2024-11-14 23:23:57.777459
17	S88990	Carlos	xxxxxxxxxxxxxcccccccccccccccc	2024-11-14 23:32:37.256803
27	1234567890	Johns	กกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกกก	2024-12-08 20:50:31.791665
\.


--
-- TOC entry 3483 (class 0 OID 17192)
-- Dependencies: 242
-- Data for Name: scholarship; Type: TABLE DATA; Schema: public; Owner: pim_admin
--

COPY public.scholarship (id, academic_year, status, start_date, end_date, created_at, updated_at) FROM stdin;
2	2024/2024	open	2024-12-01 00:00:00	2025-12-01 00:00:00	2024-11-25 20:29:12.99224	2024-11-26 20:32:04.27591
3	2024	open	2024-08-01 00:00:00	2024-11-25 20:50:37	2024-11-26 20:03:56.473498	2024-11-26 20:58:02.525293
4	2025	open	2025-08-01 00:00:00	2025-11-25 20:50:37	2024-11-26 21:58:56.200331	\N
5	2024	open	2024-12-10 00:00:00	2024-12-12 23:59:59	2024-11-26 22:04:47.795141	2024-12-09 21:26:58.293206
\.


--
-- TOC entry 3481 (class 0 OID 17183)
-- Dependencies: 240
-- Data for Name: scholarship_img; Type: TABLE DATA; Schema: public; Owner: pim_admin
--

COPY public.scholarship_img (id, student_id, first_name, image_name, image_data, create_date, image_type) FROM stdin;
25	1234567890	Johns	S1234567_Sophia_1732900953913 (11).pdf	1MijbyPbdXWXCM7ul0JHMumEyZA43QvFm	2024-12-02 22:11:18.913498	document
\.


--
-- TOC entry 3471 (class 0 OID 16503)
-- Dependencies: 230
-- Data for Name: specialwork; Type: TABLE DATA; Schema: public; Owner: pim_admin
--

COPY public.specialwork (id, student_id, first_name, work_name, organization_name, work_type, work_description, compensation, work_dates, work_time, create_date, hour, prefix, nickname, graduate, branch, activity_date, organization_phone) FROM stdin;
1	\N	\N	\N	\N	\N	\N	5000	\N	\N	2024-12-01 20:17:47.807387	\N	Mr.	Johnny	Bachelor of Science	Engineering	\N	\N
2	\N	\N	\N	\N	\N	\N	5000	\N	\N	2024-12-01 20:17:50.943361	\N	Mr.	Johnny	Bachelor of Science	Engineering	\N	\N
3	\N	\N	\N	\N	\N	\N	5000	\N	\N	2024-12-01 20:17:51.554169	\N	Mr.	Johnny	Bachelor of Science	Engineering	\N	\N
4	\N	\N	\N	\N	\N	\N	5000	\N	\N	2024-12-01 20:17:51.984575	\N	Mr.	Johnny	Bachelor of Science	Engineering	\N	\N
5	\N	\N	\N	\N	\N	\N	5000	\N	\N	2024-12-01 20:17:59.474104	\N	Mr.	Johnny	Bachelor of Science	Engineering	\N	\N
\.


--
-- TOC entry 3459 (class 0 OID 16437)
-- Dependencies: 218
-- Data for Name: specialwork_img; Type: TABLE DATA; Schema: public; Owner: pim_admin
--

COPY public.specialwork_img (id, student_id, first_name, image_name, image_data, create_date, image_type, specialwork_id) FROM stdin;
1	S67890	ssss	sss	1XN2dYpFqCsZHLJzuyMObF-8dwwDLvsq4	2024-11-19 22:31:50.17483	test	1
2	S67890	ssss	sss	1G3gHvJAKSmFmstw3Gj4xUm43lO0tVi0Z	2024-11-24 17:59:12.897074	test	1
3	S67890	ssss	sss	15XYRvPHZtdVlJaK1C1yidAhyOehMG1yu	2024-11-24 17:59:16.362792	test	1
\.


--
-- TOC entry 3477 (class 0 OID 17003)
-- Dependencies: 236
-- Data for Name: student; Type: TABLE DATA; Schema: public; Owner: pim_admin
--

COPY public.student (id, student_id, prefix, first_name, thai_name, last_name, nickname, date_of_birth, gender, national_id, email, phone_number, faculty, field_of_study, currently_studying_year, student_type, block, current_gpa, create_date, place_of_study, other_place, current_address, student_resident, number_of_residents, current_province, current_district, current_subdistrict, current_postal_code, address_according_to_house_registration, province, district, subdistrict, postal_code, advisor_name_surname, advisor_phone_number, know_the_pim_smart_fund_from, additional_details, scholarship_received, other_scholarships, education_loan, graduated_from_school, province_school, line_id, facebook, father_name_surname, mother_name_surname, occupation_father, occupation_mother, estimate_father_monthly_income, mother_approximate_monthly_income, father_address, father_address_details, mother_address, mother_address_details, congenital_disease, paternal_memory_disorder, maternal_memory_disorder, father_status, father_status_details, maternal_status, maternal_status_details, have_siblings, woman, address_value, round_trip_travel, household_expenses, family_debt, contact_information, emergency_contact, relationship, emergency_contact_phone_number, beauty_enhancement, beauty_enhancement_details, man, person_who, parent_information, talent, primary_education, middle_school, high_school, current, special_work, hope, committee, family_history, special_request, update_date) FROM stdin;
22	6452100602	นาย	SUHAIMEE	ซูไฮมี 	กาเจ	เจ	21/11/2024	ชาย	1234567897410	Suhaimee499@gmail.com	0987231910	คณะวิศวกรรมศาสตร์และเทคโนโลยี (ET)	หลักสูตรเทคโนโลยีดิจิทัลและสารสนเทศ(DIT)	4	นักศึกษาสถาบันการจัดการปัญญาภิวัฒน์ (Walkin)	B	4.00	2024-11-21 21:14:17.482661	อื่นๆโปรดระบุ	ดาวอังคาร			\N	\N	\N	\N	\N		นนทบุรี	ปากเกร็ด	ปากเกร็ด	11120				\N															\N		\N					\N		\N			\N	\N	\N	\N	\N	\N	\N	\N	ทำเสริมความงาม	ดกกกกกกกกกกกกก				ดดกกด	กดก	กก	กด	กกดกด	ดกด				\N	\N
9	S00123	Mr.	John	จอห์น	Doe	Johnny	2000-01-15	Male	1234567890123	john.doe@example.com	0912345678	Engineering	Computer Science	4	Full-time	A1	3.75	2024-11-12 09:00:00	ABC University	\N	123 Main St, City	Yes	4	Bangkok	District 1	Subdistrict A	10100	Same as current address	Bangkok	District 1	Subdistrict A	10100	Dr. Smith	0912345679	Social Media	N/A	Academic Excellence	N/A	No	XYZ High School	Bangkok	john123	john.doe	Mr. Doe Sr.	Mrs. Doe	Engineer	Teacher	50000	30000	456 Another St, City	Apartment 101	456 Another St, City	Apartment 101	None	No	No	Alive	Healthy	Alive	Healthy	Yes	No	Permanent	Public Transport	20000	100000	0912345678	Jane Doe	Sister	0987654321	ทำเสริมความงาม	\N	Yes	N/A	Provided	Music	ABC Primary School	XYZ Middle School	XYZ High School	University Student	Volunteer	To graduate with honors	Student Council	None	N/A	2024-11-21 21:27:48.082929
26	S67890	Ms.	Sara	ซาร่า	Smith	Sally	2000-08-15	Female	9876543210987	sara.smith@example.com	088-7654321	Business	Marketing	3	Full-time	B2	3.95	2024-11-24 17:30:40.031546	University of ABC	Not applicable	456 Secondary Street, City	Yes	2	Chiang Mai	District C	Subdistrict D	50200	Same as current address	Chiang Mai	District C	Subdistrict D	50200	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	ทำเสริมความงาม	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	2024-11-12 09:45:00
24	S001234	Mr.	John	จอห์น	Doe	Johnny	23/11/2024	Male	1234567890123	john.doe@example.com	0912345678	Engineering	Computer Science	4	Full-time	A1	3.75	2024-11-21 21:28:13.921516	ABC University	\N	123 Main St, City	Yes	4	Bangkok	District 1	Subdistrict A	10100	Same as current address	Bangkok	District 1	Subdistrict A	10100	Dr. Smith	0912345679	Social Media	N/A	Academic Excellence	N/A	No	XYZ High School	Bangkok	john123	john.doe	Mr. Doe Sr.	Mrs. Doe	Engineer	Teacher	50000	30000	456 Another St, City	Apartment 101	456 Another St, City	Apartment 101	None	No	No	Alive	Healthy	Alive	Healthy	Yes	No	Permanent	Public Transport	20000	100000	0912345678	Jane Doe	Sister	0987654321	ทำเสริมความงาม	\N	Yes	N/A	Provided	Music	ABC Primary School	XYZ Middle School	XYZ High School	University Student	Volunteer	To graduate with honors	Student Council	None	N/A	2024-11-23 00:22:52.977863
30	S010	นาย	Johns	ซูไฮมี 	KAJAE	เจ	04/12/2024	ชาย	1234567897410	suhaimee499@gmail.com	0984963270	คณะการจัดการธุรกิจอาหาร (FBM)	การจัดการธุรกิจอาหาร	กำลังศึกษาอยู่ปี 1	โครงการโรงเรียนพี่โรงเรียนน้อง	B	4.00	2024-12-04 22:57:58.318304	แจ้งวัฒนะ		14	บ้านตนเอง	5	\N	\N	\N	\N	55	นนทบุรี	ปากเกร็ด	ปากเกร็ด	11120	ดดดด	02222257	ทีมแนะแนว	\N	50	50	กยศ	โรง	นครนายก			ฟ	ฟ	efssd	ฟฟฟฟ	ฟ	ฟ	ที่อยุ่เดียวกับนักศึกษา		ที่อยุ่เดียวกับนักศึกษา		ฟ	ฟฟ	ฟฟ	มีชีวิตอยู่		มีชีวิตอยู่		ฟ	ฟ	ฟ	ฟฟ	ฟ	ฟ	ฟ	ฟ	ฟ	ฟ	ไม่		ฟ	ฟฟ	ฟ										\N	2024-12-08 19:15:27.214817
29	1234567890558	นาย	Johns	ซูไฮมี 	กาเจ	เจ	25/12/2024			suhaimee499@gmail.com							\N	2024-11-24 21:40:20.567637	\N	\N	14	บ้านตนเอง	5	\N	\N	\N	\N	55	นนทบุรี	ปากเกร็ด	ปากเกร็ด	11120	\N	\N	\N	\N	\N	\N	\N	\N	\N	Test	SuhaimeeKajae	sfdf	dfdf	efssd	fsdf	dfdf	dfd	ที่อยู่อื่น	555	ที่อยุ่เดียวกับนักศึกษา		ไมมี	\N		เสียชีวิต	04/12/2024	เสียชีวิต	06/12/2024	4	0	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	4	3	0	\N	\N	\N	\N	\N	\N	\N	\N			2024-12-06 23:58:25.081301
\.


--
-- TOC entry 3463 (class 0 OID 16455)
-- Dependencies: 222
-- Data for Name: students_img; Type: TABLE DATA; Schema: public; Owner: pim_admin
--

COPY public.students_img (id, student_id, first_name, image_name, image_data, create_date, image_type, register_id) FROM stdin;
151	S67890	Sara	payment.png,request-for-proposal.png	1fUbUKqKIZ8WrIUVjXAwNr8YbYTUQqHpD	2024-11-19 22:50:04.950559	uploadPictureHouse	21
152	S67890	Sara	payment.png,request-for-proposal.png	1Fwl-37Tro6UWEh8fuDirYeJ9x94PwoX7	2024-11-19 22:50:08.089221	uploadPictureHouse	21
153	S67890	Sara	request.png	1-L3OBNsJvWJQ3OoVJmVA26EUq9IQZvDy	2024-11-19 22:50:12.837926	volunteerPictures	21
154	S67890	Sara	email.png	1_9F0guR7EfHhiE9xbz_M-6_w07L8tQ6b	2024-11-19 22:50:15.738527	studentPicture	21
155	S67890	Sara	student-registration.pdf	11vFas9sA0sKe93KeWHEVDyv1L8zcKSvS	2024-11-19 22:50:21.421476	PDF	21
156	6452100602	SUHAIMEE	request-for-proposal.png,approval.png	1z7_HMAnnI4vEXgZO6cRylHp2ozYkxtHk	2024-11-21 21:14:21.867226	uploadPictureHouse	22
157	6452100602	SUHAIMEE	request-for-proposal.png,approval.png	1f2sS5RRGL3nL9-NB_h7DDIC2XRMDk_-g	2024-11-21 21:14:24.943329	uploadPictureHouse	22
158	6452100602	SUHAIMEE	request.png	1XDLdjuauo7x2AUufv4SOJTmtRJi9k0wT	2024-11-21 21:14:28.42104	volunteerPictures	22
159	6452100602	SUHAIMEE	email.png	1UKBwW95lcZBAR1kbO2q6Xi2suSymeZ6z	2024-11-21 21:14:31.438147	studentPicture	22
160	6452100602	SUHAIMEE	student-registration.pdf	1h9y1TQPV4S0Lg6ZDrt6usAoIAz30dOBN	2024-11-21 21:14:36.690656	PDF	22
165	S001234	John	student-registration.pdf	1eH23Bp0ZUgUYRC_ZgrGhJNb7C3VrM3aC	2024-11-22 23:24:23.651934	PDF	24
136	55558	ssss	sss	1oNmBKOcaTP65qJjGc1NmFt2P8lAhlbPN	2024-11-18 22:00:44.109135	test	5
166	S001234	John	beautiful-young-woma.jpg,istockphoto.jpg	1NNjuy6Xfyo4ECg213JUiFWCePoOBhv9N	2024-11-23 00:05:36.778729	uploadPictureHouse	24
167	S001234	John	beautiful-young-woma.jpg,istockphoto.jpg	1kGedLkS2wjY3prUfsd0cDzGwkr3jLGuZ	2024-11-23 00:05:39.912378	uploadPictureHouse	24
168	S001234	John	Coca-cat.jpg	1CSViCVK3i61CbuL1b1lyqJUrQCiTKcnh	2024-11-23 00:05:43.569887	volunteerPictures	24
169	S001234	John	email.png	1_PHPNeI3X5U9k3qo75xZZYln4e7I4UIU	2024-11-23 00:05:46.178418	studentPicture	24
170	S001234	John	student-registration.pdf	1ciSRz5CeeB7i-wVgosz4QZdaSqK6ncZ8	2024-11-23 00:05:50.690595	PDF	24
171	S001234	John	beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg	1xSegMFa3vL7yILVQm4kaOetEnpdJu28k	2024-11-23 00:18:34.384133	uploadPictureHouse	24
172	S001234	John	beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg	1TkwCHjyQgeHXplB6rjMXYGlCaVK5s39y	2024-11-23 00:18:37.486682	uploadPictureHouse	24
173	S001234	John	student-registration.pdf	1dZNn9g1SKEOt4uwJJiGmNLfFOSncPZzE	2024-11-23 00:18:42.447997	PDF	24
174	S001234	John	beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg	1XV5TUdl4gr4cV9E0lxLMV7ocXdCMf4dJ	2024-11-23 00:22:56.601585	uploadPictureHouse	24
175	S001234	John	beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg	13AB-XxO66DSbUPdXaOMYR8e1_C44D8Ly	2024-11-23 00:22:59.710207	uploadPictureHouse	24
176	S001234	John	beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg	1gnmFvKZkl3Pv0M-FOjMLP7rR5CsPTYMA	2024-11-23 00:23:02.830426	uploadPictureHouse	24
177	S001234	John	beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg,beautiful-young-woma.jpg,istockphoto.jpg	1nrMJUgaGFDKwqqQrxTWJk9pICLrrKRWY	2024-11-23 00:23:06.12177	uploadPictureHouse	24
178	S001234	John	student-registration.pdf	1wpOqVMKJ5dc2pSmr8V3S2oD6ad1YzziQ	2024-11-23 00:23:11.481878	PDF	24
179	S67890	ssss	sss	1Nn1YSUjLVfOrRHNO5eVcS3EcTDWcbSIf	2024-11-24 18:03:01.21831	test	5
180	S67890	ssss	sss	1fH2am_y8N8hou7b-wgwCcY5eNi2thnqA	2024-11-24 18:03:34.899981	test	5
181	S67890	ssss	sss	1ngbyYLHMjuO8OvJOiCQtYtQ50gDoO78Z	2024-11-24 18:03:39.636441	test	5
182	S67890	ssss	sss	1FEt_AE8cbZb8n6-g2bSrkKKPl2aX2ho-	2024-11-24 18:03:42.912406	test	5
183	S67890	ssss	sss	1YAx55lKRKowHJfK728SJtCAaq6qGX7QS	2024-11-24 18:03:47.230915	test	5
184	S67890	ssss	sss	1L2V1jTby8S-5SAT-JqDB52j6E_OPdpne	2024-11-24 18:03:50.468065	test	5
185	S67890	ssss	sss	1VjvKUYb-B1htRVEJo43RzLFRpbruQ52O	2024-11-24 18:03:53.427811	test	5
186	S67890	ssss	sss	1CQkdu8bXfxRR88O0Anug-amU_16L7oZ0	2024-11-24 18:03:56.652562	test	5
187	S67890	ssss	student-registration (26),student-registration (27),student-registration (28),student-registration (29)	1XuoJKmeUzgCQKow5X2tmxCkBAwfpMAcL	2024-11-24 18:05:50.538163	test	5
188	S67890	ssss	student-registration (26),student-registration (27),student-registration (28),student-registration (29)	1NZemN9qYrRk9XGfoJEZy3eKnIMFcwZEJ	2024-11-24 18:05:56.511981	test	5
189	S67890	ssss	student-registration (26),student-registration (27),student-registration (28),student-registration (29)	1c14HbB4hMo9THpzxe_VuBZA0ijggB0K5	2024-11-24 18:06:01.834025	test	5
190	S67890	ssss	student-registration (26),student-registration (27),student-registration (28),student-registration (29)	1ZSpvjEDn0mjEG8Jb_STq5x_m3yRp5bnZ	2024-11-24 18:06:06.477846	test	5
191	S67890	ssss	student-registration (26),student-registration (27),student-registration (28),student-registration (29)	1xdWIGODl2USSHXPPhR9jfJn18ePMtMNE	2024-11-24 18:06:10.610175	test	5
192	S67890	ssss	student-registration (26),student-registration (27),student-registration (28),student-registration (29)	1URmvwJjZWUlEEGXSf6OwnJXoHSBfE3DD	2024-11-24 18:06:14.842122	test	5
193	S67890	ssss	student-registration (26),student-registration (27),student-registration (28),student-registration (29)	1hiOhbnh1PNlASQBhMcUOMU16m7Ll-zuE	2024-11-24 18:06:18.22342	test	5
210	1234567890555	Sophia	beautiful-young-woma.jpg	1yBpotbLmlRjO8Yar3VHJF3d2Z5rmmTLT	2024-11-24 21:32:24.875214	uploadPictureHouse	27
211	1234567890555	Sophia	email.png	1P1sqATDwS37JwzK6BpuCW8fm-7IHYrAN	2024-11-24 21:32:27.294891	uploadPictureHouse	27
212	1234567890555	Sophia	Coca-cat.jpg	1rKV7Cvxdm2F_FhJS8SRPxgSB1pPXN0ab	2024-11-24 21:32:30.261384	volunteerPictures	27
213	1234567890555	Sophia	istockphoto.jpg	13y4u1UBJCdOFXB2yag-_HclvZVNsKF6W	2024-11-24 21:32:32.989777	studentPicture	27
214	1234567890555	Sophia	student-registration.pdf	1VytvW7B5kHXokyPhpnXhX29LRUzraK2v	2024-11-24 21:32:43.060044	PDF	27
225	1234567890558	Johns	student-registration.pdf	13D6zt-cKR6ij7HpSPAqXMY0rtbvBTnRL	2024-11-24 21:40:40.054121	PDF	29
226	S010	Johns	Coca-cat.jpg	1US5rtXYdFu5aa8MgsF4hvneppCyhyX5Y	2024-12-04 22:58:03.091835	uploadPictureHouse	30
227	S010	Johns	istockphoto.jpg	1Zi7u4IVLJGvGdkcsEE7148G5mYSA6-4J	2024-12-04 22:58:06.708544	uploadPictureHouse	30
228	S010	Johns	download-pdf.png	1pBV_3WW5ZqjAJ0uF3B-sx6fy7vMsmISB	2024-12-04 22:58:09.444829	volunteerPictures	30
229	S010	Johns	beautiful-young-woma.jpg	1t4m3w63e3UEISTqZsepfVuI0FJLJF3Y1	2024-12-04 22:58:12.809499	studentPicture	30
230	S010	Johns	student-registration.pdf	1ACSf1cSPuOUI-UjcHlK49eYfgh5hxVsV	2024-12-04 22:58:18.438384	PDF	30
231	1234567890558	Johns	student-registration.pdf	1TiYGD8Ub1v-_TiRhtf_0NXRvMov8xckC	2024-12-06 22:51:02.548796	PDF	29
234	1234567890558	Johns	email.png	1IFc79g9l2h_R3ZJpiuq5P11ItVVhhT6b	2024-12-06 23:44:32.591342	volunteerPictures	29
235	1234567890558	Johns	request.png	1hoX3KbgC8ODqHkI4708k2Zqyv_rDCN0J	2024-12-06 23:44:36.744211	volunteerPictures	29
237	1234567890558	Johns	student-registration.pdf	1Nksi73uc0jf0zrNBzyoHSb9ebeA5D1bs	2024-12-06 23:44:48.070354	PDF	29
239	1234567890558	Johns	student-registration.pdf	1_PvNh8mLJHem7hBnihiXw4IZN8_uQvKQ	2024-12-06 23:47:54.195116	PDF	29
240	1234567890558	Johns	student-registration.pdf	1ZjXI_J9R5T0PBS9i2ghnyDyP_ycfbLqJ	2024-12-06 23:58:34.088382	PDF	29
241	S010	Johns	student-registration.pdf	1dWFHV_H06F7CQbs7Bjp1f4jRii_Im-4m	2024-12-07 23:24:11.820247	PDF	30
242	S010	Johns	student-registration.pdf	1e3psXdHpIUHQlwhvxaUVxAnLYQ8-8oK1	2024-12-08 19:15:35.03392	PDF	30
\.


--
-- TOC entry 3467 (class 0 OID 16480)
-- Dependencies: 226
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: pim_admin
--

COPY public.users (id, email, password, token, create_date, updated_date, update_date) FROM stdin;
1	Suhaimee499@gmail.com	$2a$10$WByoir0ishgC0RFu5NTWj.n5Phnwt.SjZ1GJmCj/RFYFzcw58QE3e	eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJTdWhhaW1lZTQ5OUBnbWFpbC5jb20iLCJpYXQiOjE3MzAzMDM3NjEsImV4cCI6MTczMDM5MDE2MX0.IxflRTEIfLZdTX_nLI80cIPGmBz3OYiGyrz2PByNzDOth-YeS7xhRn0m0ijTbvHR53v9s6VT6wMp2Zvt4Ltamw	2024-10-30 22:56:01.55406	2024-10-30 22:56:01.608934	\N
\.


--
-- TOC entry 3469 (class 0 OID 16494)
-- Dependencies: 228
-- Data for Name: volunteeractivity; Type: TABLE DATA; Schema: public; Owner: pim_admin
--

COPY public.volunteeractivity (id, student_id, first_name, activity_name, organization_name, organization_phone, activity_description, activity_date, hours, create_date, prefix, nickname, graduate, branch) FROM stdin;
1	12345	John	Community Service	Helping Hands	555-1234	Volunteer work at local shelters.	2024-11-01	5	2024-11-01 07:00:00	Volunteer	Johnny	2023	Computer Science
2	12345	John	Community Service	Helping Hands	555-1234	Volunteer work at local shelters.	2024-11-01	5	2024-11-01 07:00:00	Volunteer	Johnny	2023	Computer Science
3	12345	John	Community Service	Helping Hands	555-1234	Volunteer work at local shelters.	2024-11-01	5	2024-11-01 07:00:00	Volunteer	Johnny	2023	Computer Science
4	12345	John	Community Service	Helping Hands	555-1234	Volunteer work at local shelters.	2024-11-01	5	2024-11-01 07:00:00	Volunteer	Johnny	2023	Computer Science
5	12345	John	Community Service	Helping Hands	555-1234	Volunteer work at local shelters.	2024-11-01	5	2024-11-01 07:00:00	Volunteer	Johnny	2023	Computer Science
6	12345	John	Community Service	Helping Hands	555-1234	Volunteer work at local shelters.	2024-11-01	5	2024-11-01 07:00:00	Volunteer	Johnny	2023	Computer Science
7	12345	John	Community Service	Helping Hands	555-1234	Volunteer work at local shelters.	2024-11-01	5	2024-11-01 07:00:00	Volunteer	Johnny	2023	Computer Science
8	12345	John	Community Service	Helping Hands	555-1234	Volunteer work at local shelters.	2024-11-01	5	2024-11-01 07:00:00	Volunteer	Johnny	2023	Computer Science
9	12345	John	Community Service	Helping Hands	555-1234	Volunteer work at local shelters.	2024-11-01	5	2024-11-01 07:00:00	Volunteer	Johnny	2023	Computer Science
10	6452100602	ซูไฮมี	ทาอทอานกท	อทานอทาน	 0258741963		24/11/2024	4	2024-11-24 19:34:55.494	ชาย	กาจ	ชั้นปีที่ 4	DIT
11	6452100602	ซูไฮมี	ทาอทอานกท	อทานอทาน	 0258741963		24/11/2024	4	2023-05-04 19:35:02.22	ชาย	กาจ	ชั้นปีที่ 4	DIT
\.


--
-- TOC entry 3461 (class 0 OID 16446)
-- Dependencies: 220
-- Data for Name: volunteeractivity_img; Type: TABLE DATA; Schema: public; Owner: pim_admin
--

COPY public.volunteeractivity_img (id, student_id, first_name, image_name, image_data, create_date, image_type, volunteerid, volunteer_id) FROM stdin;
2	12345	John	request-for-proposal.png	1Mq8kLyp3o-UCGJge_2YmS3S1HqBMyszQ	2024-11-12 23:53:25.428525	uploadVolunteer	\N	1
3	12345	John	approval.png	1V4Kq937OvqN0RbxR5PFQVoiS3if-y7jj	2024-11-12 23:58:08.527182	uploadVolunteer	\N	1
4	6452100602	ซูไฮมี	beautiful-young-woma.jpg,Coca-cat.jpg	1zVlT9GZs9q02HECuybqVPRLQIq9EUhH9	2024-11-24 19:34:58.794376	Volunteer	\N	10
5	6452100602	ซูไฮมี	beautiful-young-woma.jpg,Coca-cat.jpg	1_-YcJ6A_mllRYwqjCUmUjyNcdttpfqgd	2024-11-24 19:35:02.293026	Volunteer	\N	10
6	6452100602	ซูไฮมี	beautiful-young-woma.jpg,Coca-cat.jpg	19am4ddfVMjPD16S3TYcKZLCbcObND-kZ	2024-11-24 19:35:04.778531	Volunteer	\N	11
7	6452100602	ซูไฮมี	beautiful-young-woma.jpg,Coca-cat.jpg	1XiJ4kYBVrdl4ct8sDDr2G31iBp2Zmkid	2024-11-24 19:35:08.396044	Volunteer	\N	11
8	6452100602	ซูไฮมี	request.png	15_OSpp7F0ivsRdsCGR2L2ncwEjsp509e	2024-11-24 19:45:05.843237	uploadVolunteer	\N	11
10	6452100602	ซูไฮมี	email.png,request.png	1mIrnBZ76H_TeVoLiVvW5Tu7O2utMeYAg	2024-11-24 19:45:57.400937	uploadVolunteer	\N	10
\.


--
-- TOC entry 3501 (class 0 OID 0)
-- Dependencies: 237
-- Name: application_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pim_admin
--

SELECT pg_catalog.setval('public.application_history_id_seq', 79, true);


--
-- TOC entry 3502 (class 0 OID 0)
-- Dependencies: 233
-- Name: post_news_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pim_admin
--

SELECT pg_catalog.setval('public.post_news_id_seq', 6, true);


--
-- TOC entry 3503 (class 0 OID 0)
-- Dependencies: 231
-- Name: rankin_activityk_entities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pim_admin
--

SELECT pg_catalog.setval('public.rankin_activityk_entities_id_seq', 1, false);


--
-- TOC entry 3504 (class 0 OID 0)
-- Dependencies: 223
-- Name: request_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pim_admin
--

SELECT pg_catalog.setval('public.request_id_seq', 27, true);


--
-- TOC entry 3505 (class 0 OID 0)
-- Dependencies: 241
-- Name: scholarship_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pim_admin
--

SELECT pg_catalog.setval('public.scholarship_id_seq', 5, true);


--
-- TOC entry 3506 (class 0 OID 0)
-- Dependencies: 239
-- Name: scholarship_img_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pim_admin
--

SELECT pg_catalog.setval('public.scholarship_img_id_seq', 25, true);


--
-- TOC entry 3507 (class 0 OID 0)
-- Dependencies: 229
-- Name: specialwork_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pim_admin
--

SELECT pg_catalog.setval('public.specialwork_id_seq', 5, true);


--
-- TOC entry 3508 (class 0 OID 0)
-- Dependencies: 217
-- Name: specialwork_img_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pim_admin
--

SELECT pg_catalog.setval('public.specialwork_img_id_seq', 3, true);


--
-- TOC entry 3509 (class 0 OID 0)
-- Dependencies: 235
-- Name: student_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pim_admin
--

SELECT pg_catalog.setval('public.student_id_seq', 30, true);


--
-- TOC entry 3510 (class 0 OID 0)
-- Dependencies: 221
-- Name: students_img_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pim_admin
--

SELECT pg_catalog.setval('public.students_img_id_seq', 242, true);


--
-- TOC entry 3511 (class 0 OID 0)
-- Dependencies: 225
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pim_admin
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- TOC entry 3512 (class 0 OID 0)
-- Dependencies: 227
-- Name: volunteeractivity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pim_admin
--

SELECT pg_catalog.setval('public.volunteeractivity_id_seq', 11, true);


--
-- TOC entry 3513 (class 0 OID 0)
-- Dependencies: 219
-- Name: volunteeractivity_img_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pim_admin
--

SELECT pg_catalog.setval('public.volunteeractivity_img_id_seq', 10, true);


--
-- TOC entry 3308 (class 2606 OID 17022)
-- Name: application_history application_history_pkey; Type: CONSTRAINT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.application_history
    ADD CONSTRAINT application_history_pkey PRIMARY KEY (id);


--
-- TOC entry 3304 (class 2606 OID 16847)
-- Name: post_news post_news_pkey; Type: CONSTRAINT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.post_news
    ADD CONSTRAINT post_news_pkey PRIMARY KEY (id);


--
-- TOC entry 3302 (class 2606 OID 16519)
-- Name: rankin_activityk_entities rankin_activityk_entities_pkey; Type: CONSTRAINT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.rankin_activityk_entities
    ADD CONSTRAINT rankin_activityk_entities_pkey PRIMARY KEY (id);


--
-- TOC entry 3310 (class 2606 OID 17190)
-- Name: scholarship_img scholarship_img_pkey; Type: CONSTRAINT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.scholarship_img
    ADD CONSTRAINT scholarship_img_pkey PRIMARY KEY (id);


--
-- TOC entry 3312 (class 2606 OID 17199)
-- Name: scholarship scholarship_pkey; Type: CONSTRAINT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.scholarship
    ADD CONSTRAINT scholarship_pkey PRIMARY KEY (id);


--
-- TOC entry 3288 (class 2606 OID 16444)
-- Name: specialwork_img specialwork_img_pkey; Type: CONSTRAINT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.specialwork_img
    ADD CONSTRAINT specialwork_img_pkey PRIMARY KEY (id);


--
-- TOC entry 3300 (class 2606 OID 16528)
-- Name: specialwork specialwork_pkey; Type: CONSTRAINT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.specialwork
    ADD CONSTRAINT specialwork_pkey PRIMARY KEY (id);


--
-- TOC entry 3306 (class 2606 OID 17010)
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (id);


--
-- TOC entry 3292 (class 2606 OID 16462)
-- Name: students_img students_img_pkey; Type: CONSTRAINT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.students_img
    ADD CONSTRAINT students_img_pkey PRIMARY KEY (id);


--
-- TOC entry 3294 (class 2606 OID 16491)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 3296 (class 2606 OID 16489)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3290 (class 2606 OID 16453)
-- Name: volunteeractivity_img volunteeractivity_img_pkey; Type: CONSTRAINT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.volunteeractivity_img
    ADD CONSTRAINT volunteeractivity_img_pkey PRIMARY KEY (id);


--
-- TOC entry 3298 (class 2606 OID 16759)
-- Name: volunteeractivity volunteeractivity_pkey; Type: CONSTRAINT; Schema: public; Owner: pim_admin
--

ALTER TABLE ONLY public.volunteeractivity
    ADD CONSTRAINT volunteeractivity_pkey PRIMARY KEY (id);


-- Completed on 2024-12-16 22:28:27

--
-- PostgreSQL database dump complete
--

